
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[225] =
    {   0,
       46,   46,    0,    0,   54,   50,    2,    1,   29,   50,
       23,   28,   48,   30,   31,   22,   36,   22,   50,   23,
        3,   37,   24,   27,   24,   40,   34,   35,   28,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   32,
       28,   33,   53,   24,   51,   38,    0,   26,   48,   47,
       48,   25,    4,   52,    0,    4,    3,   46,   46,   28,
       40,   40,   40,   40,   40,   40,   40,   11,   40,   40,
       40,   16,   40,   40,   40,   40,   40,   51,    0,   48,
        5,   48,   48,   48,   48,    0,    4,    0,   52,    0,
        0,   41,    0,   41,    0,    4,    0,    0,    0,    4,

       40,   40,   40,   40,   40,   40,   40,   40,   15,   17,
       40,   40,   40,   40,   39,    0,   49,   48,   48,    5,
       44,    0,    0,    0,    4,   43,    0,    0,   41,    0,
       41,    4,    0,    0,    4,   45,   45,    0,   40,    7,
        8,   40,   40,   40,   13,   40,   40,   40,   21,   40,
       44,   44,   45,   45,    0,   41,    0,    0,   42,    0,
       42,    0,    0,    0,    4,    0,   45,    0,    0,   45,
        6,   40,   40,   40,   14,   40,   40,   20,   44,    0,
       45,    0,    0,   45,    0,    0,   45,   45,    0,    0,
       45,    0,    0,   45,   40,   40,   12,   18,   19,    0,

       45,    0,    0,   45,    0,   45,    0,    0,   45,    0,
       45,   40,   10,    0,   45,    0,   45,    0,    0,   45,
        9,    0,   45,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       23,   23,   23,   23,   23,   23,   23,    9,   24,   25,
       26,   27,    9,    9,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       30,   31,   32,   33,   28,    9,   34,   35,   36,   37,

       38,   39,   28,   40,   41,   28,   42,   43,   28,   44,
       45,   28,   28,   46,   47,   48,   49,   50,   51,   28,
       28,   28,   52,   53,   54,    9,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    2,    3,    3,    3,    3,    3,
        3,    3,    4,    3,    3,    3,    3,    3,    3,    5,
        3,    6,    6,    3,    3,    3,    3,    6,    6,    3,
        3,    3,    3,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    3,    3,    3
    } ;

static const flex_int16_t yy_base[237] =
    {   0,
        0,    0,    0,    0,  319,  727,  727,  727,  269,   47,
      727,  278,   43,  727,  727,  249,  727,  233,   35,   43,
       43,  727,   35,  223,   41,   47,  727,  727,  727,   53,
       57,   60,   63,   65,   70,   73,   67,   78,   81,  727,
      186,  727,  727,  727,   63,  727,  121,  727,   94,  727,
      164,  727,   93,  203,  127,  113,  124,   97,  156,  727,
        0,  105,  116,  127,  158,  141,  118,  160,  166,  171,
      174,  168,  178,  182,  184,  195,  199,  137,  212,  135,
      727,  233,  171,  198,  174,  201,  209,  231,  154,  140,
      232,  727,  156,  255,  268,  262,  270,  239,  205,  274,

      211,  276,  234,  221,  279,  253,  282,  284,  286,  288,
      293,  299,  301,  303,  727,  345,  727,  304,    0,  727,
      307,  309,  314,  317,  332,  727,  346,  363,  354,  130,
      372,  374,  382,  321,  340,  349,  384,  392,  394,  396,
      398,  401,  403,  405,  407,  409,  412,  415,  417,  421,
      427,  433,  438,  440,  449,  727,  109,  470,  727,   81,
      474,  480,  467,  423,  471,  480,  484,  493,  442,  473,
      495,  497,  501,  504,  506,  508,  510,  512,  516,  526,
      524,  537,  535,  541,  563,   74,  548,  550,  559,  552,
      561,  568,  570,  572,  574,  576,  578,  580,  582,  584,

      586,  593,  591,  595,  603,  605,  613,  615,  617,  619,
      622,  624,  626,  628,  630,  632,  634,  641,  643,  645,
      647,  649,  651,  727,  674,  680,  684,  686,   67,  690,
      696,  702,   56,  708,  714,  720
    } ;

static const flex_int16_t yy_def[237] =
    {   0,
      224,    1,  225,  225,  224,  224,  224,  224,  224,  226,
      224,  224,  227,  224,  224,  224,  224,  224,  224,  224,
      228,  224,  224,  224,  224,  229,  224,  224,  224,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  224,
      224,  224,  224,  224,  226,  224,  224,  224,  230,  224,
      230,  224,  224,  231,  232,  224,  228,  228,  228,  224,
      233,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  234,  224,  230,
      224,  230,  230,  224,   82,  224,  224,  224,  231,  231,
      232,  224,  224,  232,  235,  224,  224,  224,  224,  224,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  224,  224,  224,  230,   82,  224,
      224,  224,  224,  224,  224,  224,  235,  235,  236,  224,
      235,  224,  224,  224,  224,  224,  224,  224,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      224,  224,  224,  224,  224,  224,  224,  236,  224,  224,
      236,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      229,  229,  229,  229,  229,  229,  229,  229,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  229,  229,  229,  229,  229,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  229,  229,  224,  224,  224,  224,  224,  224,  224,
      229,  224,  224,    0,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224
    } ;

static const flex_int16_t yy_nxt[782] =
    {   0,
        6,    7,    8,    7,    7,    7,    9,   10,    6,    6,
       11,   12,   13,   14,   15,   11,   16,   17,   18,   19,
       20,   21,   21,   22,   23,   24,   25,   26,   26,   27,
        6,   28,   29,   26,   30,   31,   32,   33,   34,   26,
       35,   26,   26,   26,   26,   36,   37,   26,   26,   38,
       39,   40,   41,   42,   46,   50,   53,   53,   54,   60,
       44,   61,   56,   55,   57,   57,   44,   60,   61,   61,
       46,   59,   62,   51,   61,   61,  158,   47,   61,   61,
       59,   61,   61,  159,   61,   61,   61,   61,   61,   61,
       64,   61,   61,   47,   61,   61,   65,   67,   63,   61,

       61,   66,   61,   61,   68,   69,   81,   70,   72,   71,
       74,  156,   86,   73,   87,   87,  224,   75,  224,  224,
       77,   88,   76,   78,   82,   79,   61,   61,   45,   92,
       88,   93,  129,   45,   96,   96,   94,   61,   61,   61,
       61,   97,   45,   56,  115,   57,   57,  117,   61,   61,
       97,   45,   59,  101,   45,   45,  105,   95,   92,   45,
      126,   59,   61,   61,   45,   82,   45,  116,   45,   90,
       45,   83,   98,  102,   98,   99,   84,  100,  100,   61,
       61,   61,   61,   81,  104,   83,   81,   61,   61,   61,
       61,  103,   61,   61,   85,   61,   61,   83,   83,   61,

       61,   82,   83,   61,   61,   61,   61,   83,  106,   83,
      120,   83,  107,   83,   78,  108,   61,   61,   90,  109,
       61,   61,  121,  121,  112,  110,  136,  136,  122,  111,
       87,   87,   61,   61,   92,  113,   93,   88,   48,  114,
      118,   94,   61,   61,  139,  117,   88,  123,   44,  123,
      124,   52,  125,  125,  118,   61,   61,   92,   99,   93,
      100,  100,   95,  119,   94,   52,  118,  118,  142,  128,
      129,  118,  130,  128,   61,   61,  118,  131,  118,  141,
      118,   86,  118,  132,  132,   95,  134,  144,  134,   48,
      133,  135,  135,  137,   44,  100,  100,   61,   61,  133,

       61,   61,  138,   61,   61,   61,   61,   61,   61,   61,
       61,  138,  143,  140,   61,   61,  117,  146,  224,  145,
       61,   61,   61,   61,   61,   61,   86,  224,  151,  151,
      152,  152,  224,  124,   82,  125,  125,  149,  153,  153,
      224,  147,  135,  135,  224,  150,  148,   78,  156,   79,
      157,  154,   78,  125,  125,  131,  159,   78,  160,  224,
      155,  135,  135,  161,  128,  129,   78,  130,  128,  155,
      136,  136,  131,  224,  156,   78,  157,  166,   78,   78,
      224,  131,  224,   78,  162,  224,  166,  224,   78,  224,
       78,  224,   78,  122,   78,  132,  132,  224,  163,  224,

      163,  164,  133,  165,  165,  167,  167,  224,  169,  224,
      169,  133,  168,  170,  170,   61,   61,   61,   61,   61,
       61,  168,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  224,   61,   61,  171,   61,   61,   61,   61,
      224,  172,   61,   61,  187,  187,  122,  174,  151,  151,
      177,  173,   86,  224,  179,  179,  175,  176,  178,  153,
      153,  181,  181,  170,  170,  183,  180,  183,  182,  224,
      184,  184,  159,  224,  160,  180,  159,  182,  160,  161,
      224,  185,  158,  161,  186,  185,  164,  224,  165,  165,
      188,  224,  165,  165,  170,  170,  190,  224,  190,  189,

      162,  191,  191,  224,  162,  167,  167,  224,  189,  193,
      224,  193,  192,  224,  194,  194,   61,   61,   61,   61,
      224,  192,   61,   61,  224,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  122,  224,  179,  179,  224,
      195,  197,  200,  196,  200,  181,  181,  201,  201,  199,
      224,  198,  202,  203,  224,  203,  184,  184,  204,  204,
      224,  202,  184,  184,  185,  158,  224,  186,  185,  187,
      187,  206,  206,  191,  191,  208,  205,  208,  207,  224,
      209,  209,  191,  191,  210,  205,  210,  207,  224,  211,
      211,  194,  194,  194,  194,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,  201,  201,  201,  201,  214,
      224,  214,  204,  204,  215,  215,  204,  204,  224,  216,
      224,  216,  212,  213,  217,  217,  206,  206,  224,  219,
      224,  219,  224,  218,  220,  220,  209,  209,  209,  209,
      211,  211,  218,  211,  211,   61,   61,   61,   61,  215,
      215,  215,  215,  217,  217,  217,  217,  222,  224,  222,
      224,  221,  223,  223,  220,  220,  220,  220,   61,   61,
      223,  223,  223,  223,   43,   43,   43,   43,   43,   43,
       45,  224,   45,  224,   45,   45,   49,   49,   49,   49,
       58,   58,   80,   80,   80,   80,   89,   89,   89,   89,

       89,   89,   91,   91,   91,   91,   91,   91,   78,  224,
       78,  224,   78,   78,  127,  127,  127,  127,  127,  127,
      158,  158,  158,  158,  158,  158,    5,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224
    } ;

static const flex_int16_t yy_chk[782] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   10,   13,   19,   19,   20,   23,
       23,  233,   21,   20,   21,   21,   25,   25,   26,   26,
       45,   21,  229,   13,   30,   30,  186,   10,   31,   31,
       21,   32,   32,  160,   33,   33,   34,   34,   37,   37,
       31,   35,   35,   45,   36,   36,   31,   32,   30,   38,

       38,   31,   39,   39,   32,   33,   49,   34,   35,   34,
       36,  157,   53,   35,   53,   53,   58,   37,   58,   58,
       39,   53,   38,   47,   49,   47,   62,   62,   47,   55,
       53,   55,  130,   47,   56,   56,   55,   63,   63,   67,
       67,   56,   47,   57,   78,   57,   57,   80,   64,   64,
       56,   47,   57,   63,   47,   47,   67,   55,   93,   47,
       90,   57,   66,   66,   47,   80,   47,   78,   47,   89,
       47,   51,   59,   64,   59,   59,   51,   59,   59,   65,
       65,   68,   68,   83,   66,   51,   85,   69,   69,   72,
       72,   65,   70,   70,   51,   71,   71,   51,   51,   73,

       73,   83,   51,   74,   74,   75,   75,   51,   68,   51,
       84,   51,   69,   51,   79,   70,   76,   76,   54,   71,
       77,   77,   86,   86,   75,   73,   99,   99,   87,   74,
       87,   87,  101,  101,   91,   76,   91,   87,   41,   77,
       82,   91,  104,  104,  101,   82,   87,   88,   24,   88,
       88,   18,   88,   88,   82,  103,  103,   94,   98,   94,
       98,   98,   91,   82,   94,   16,   82,   82,  104,   95,
       95,   82,   95,   95,  106,  106,   82,   95,   82,  103,
       82,   96,   82,   96,   96,   94,   97,  106,   97,   12,
       96,   97,   97,  100,    9,  100,  100,  102,  102,   96,

      105,  105,  100,  107,  107,  108,  108,  109,  109,  110,
      110,  100,  105,  102,  111,  111,  118,  108,    5,  107,
      112,  112,  113,  113,  114,  114,  121,    0,  121,  121,
      122,  122,    0,  123,  118,  123,  123,  113,  124,  124,
        0,  111,  134,  134,    0,  114,  112,  116,  127,  116,
      127,  125,  116,  125,  125,  127,  129,  116,  129,    0,
      125,  135,  135,  129,  128,  128,  116,  128,  128,  125,
      136,  136,  128,    0,  131,  116,  131,  136,  116,  116,
        0,  131,    0,  116,  129,    0,  136,    0,  116,    0,
      116,    0,  116,  132,  116,  132,  132,    0,  133,    0,

      133,  133,  132,  133,  133,  137,  137,    0,  138,    0,
      138,  132,  137,  138,  138,  139,  139,  140,  140,  141,
      141,  137,  142,  142,  143,  143,  144,  144,  145,  145,
      146,  146,    0,  147,  147,  139,  148,  148,  149,  149,
        0,  142,  150,  150,  164,  164,  151,  144,  151,  151,
      148,  143,  152,    0,  152,  152,  146,  147,  150,  153,
      153,  154,  154,  169,  169,  155,  153,  155,  154,    0,
      155,  155,  158,    0,  158,  153,  161,  154,  161,  158,
        0,  162,  162,  161,  162,  162,  163,    0,  163,  163,
      165,    0,  165,  165,  170,  170,  166,    0,  166,  165,

      158,  166,  166,    0,  161,  167,  167,    0,  165,  168,
        0,  168,  167,    0,  168,  168,  171,  171,  172,  172,
        0,  167,  173,  173,    0,  174,  174,  175,  175,  176,
      176,  177,  177,  178,  178,  179,    0,  179,  179,    0,
      172,  174,  180,  173,  180,  181,  181,  180,  180,  177,
        0,  176,  181,  182,    0,  182,  183,  183,  182,  182,
        0,  181,  184,  184,  185,  185,    0,  185,  185,  187,
      187,  188,  188,  190,  190,  189,  187,  189,  188,    0,
      189,  189,  191,  191,  192,  187,  192,  188,    0,  192,
      192,  193,  193,  194,  194,  195,  195,  196,  196,  197,

      197,  198,  198,  199,  199,  200,  200,  201,  201,  202,
        0,  202,  203,  203,  202,  202,  204,  204,    0,  205,
        0,  205,  195,  196,  205,  205,  206,  206,    0,  207,
        0,  207,    0,  206,  207,  207,  208,  208,  209,  209,
      210,  210,  206,  211,  211,  212,  212,  213,  213,  214,
      214,  215,  215,  216,  216,  217,  217,  218,    0,  218,
        0,  212,  218,  218,  219,  219,  220,  220,  221,  221,
      222,  222,  223,  223,  225,  225,  225,  225,  225,  225,
      226,    0,  226,    0,  226,  226,  227,  227,  227,  227,
      228,  228,  230,  230,  230,  230,  231,  231,  231,  231,

      231,  231,  232,  232,  232,  232,  232,  232,  234,    0,
      234,    0,  234,  234,  235,  235,  235,  235,  235,  235,
      236,  236,  236,  236,  236,  236,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexical_Analyzer.l"

#line 6 "Lexical_Analyzer.l"
    #include<stdio.h>
    #include<stdlib.h>
    #include<string>
    #include<iostream>
    #include "SymbolTable.h"
    using namespace std;

    int line_count=1;
    int error_count=0;
    string comment="";

    FILE *log_ = fopen("1905058_log.txt","w");
    FILE *token = fopen("1905058_token.txt","w");


    SymbolTable Table(10);

   std::string StringFormatter(const std::string str)
{
    std::string temp_s = string(str);
    std::string formatted_s = "";
    char prev_char = 0;

    for(size_t i = 1; i < temp_s.size() - 1; ++i)
    {
        if(prev_char == '\\')
        {
            prev_char = temp_s[i];

            if(temp_s[i] == '\'')
            {
                formatted_s += '\'';
            }
            else if(temp_s[i] == '\"')
            {
                formatted_s += '\"';
            }
            else if(temp_s[i] == 'n')
            {
                formatted_s += '\n';
            }
            else if(temp_s[i] == 't')
            {
                formatted_s += '\t';
            }
            else if(temp_s[i] == '\\')
            {
                formatted_s += '\\';
                prev_char = 0;
            }
            else if(temp_s[i] == 'a')
            {
                formatted_s += '\a';
            }
            else if(temp_s[i] == 'f')
            {
                formatted_s += '\f';
            }
            else if(temp_s[i] == 'r')
            {
                formatted_s += '\r';
            }
            else if(temp_s[i] == 'b')
            {
                formatted_s += '\b';
            }
            else if(temp_s[i] == 'v')
            {
                formatted_s += '\v';
            }
            else if(temp_s[i] == '0')
            {
                formatted_s += '\0';
            }
            else if(temp_s[i] == '\r')
            {
                prev_char = '\\';
            }
            else if(temp_s[i] == '\n')
            {
                
            }
        }
        else
        {
            prev_char = temp_s[i];

            if(temp_s[i] != '\\')
            {
                formatted_s += temp_s[i];
            }
        }
    }

    return formatted_s;
}

#line 792 "lex.yy.c"
/*Definitions Section*/
/*KEYWORD TOKENS*/
/*OPERATORS*/
/*TOKEN BASE*/
/*COMMENTS*/
/*CONSTANTS*/
/*CHARACTER BUILDER*/
/*ID BUILDER*/
/*STRING BUILDER*/
/*INTEGER BUILDER*/
/*FLOAT BUILDER*/
/*ERROR DETECTION*/
/*ERROR BASE*/
/*TOO MANY DECIMAL POINT ERROR EXAMPLE:1.2.345*/
/*INVALID SUFFIX OR PREFIX EXAMPLE:12abcd*/
/* ILL FORMED NUMBER EXAMPLE:11E3.5*/
/*UNFINISHED CHARACTERS EXAMPLE:‘a , ‘\n or ‘\’ */
/*UNFINISHED COMMENT*/
/*MULTI CHARACTER ERROR EXAMPLE:‘ab’ */
/*EMPTY*/
/*UNFINISHED STRING*/
/*UNRECOGNISED CHARACTER*/
/*RULES SECTION*/
#line 816 "lex.yy.c"

#define INITIAL 0
#define comment_state 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 219 "Lexical_Analyzer.l"

#line 1036 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 225 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 727 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 220 "Lexical_Analyzer.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 222 "Lexical_Analyzer.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 225 "Lexical_Analyzer.l"
{
    fprintf(token,"<CONST_INT, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <CONST_INT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 229 "Lexical_Analyzer.l"
{
     fprintf(token,"<CONST_FLOAT, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <CONST_FLOAT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 233 "Lexical_Analyzer.l"
{
    string temp= yytext;
    if(temp.length()==3)
    {
        fprintf(token,"<CONST_CHAR, %c>\n",temp[1]);
        fprintf(log_,"Line# %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,yytext);
    }
    else
    {
        char temp_ch;
        switch(temp[2])
        {
            case 'n': 
            {
                temp_ch='\n';
                break;
            }
            case 't':
            {
                temp_ch='\t';
                break;
            }
            case 'a':
            {
                temp_ch='\a';
                break;
            }
            case 'f':
            {
                temp_ch='\f';
                break;
            }
            case 'r':
            {
                temp_ch='\r';
                break;
            }
            case 'b':
            {
                temp_ch='\b';
                break;
            }
            case 'v':
            {
                temp_ch='\v';
                break;
            }
            case '0':
            {
                temp_ch='\0';
                break;
            }
            case '\'':
            {
                temp_ch='\'';
                break;
            }
            case '\"':
            {
                temp_ch='\"';
                break;
            }
            case '\\':
            {
                temp_ch='\\';
                break;
            }
        }
        fprintf(token,"<CONST_CHAR, %c>\n",temp_ch);
        fprintf(log_,"Line# %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,yytext);
    }
       
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 306 "Lexical_Analyzer.l"
{
    fprintf(token,"<BREAK, break>\n");
    fprintf(log_,"Line# %d: Token <BREAK> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 310 "Lexical_Analyzer.l"
{
    fprintf(token,"<CASE, case>\n");
    fprintf(log_,"Line# %d: Token <CASE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 314 "Lexical_Analyzer.l"
{
     fprintf(token,"<CHAR, char>\n");
    fprintf(log_,"Line# %d: Token <CHAR> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 318 "Lexical_Analyzer.l"
{
    fprintf(token,"<CONTINUE, continue>\n");
    fprintf(log_,"Line# %d: Token <CONTINUE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 322 "Lexical_Analyzer.l"
{
    fprintf(token,"<DEFAULT, default>\n");
    fprintf(log_,"Line# %d: Token <DEFAULT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 326 "Lexical_Analyzer.l"
{
    fprintf(token,"<DO, do>\n");
    fprintf(log_,"Line# %d: Token <DO> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 330 "Lexical_Analyzer.l"
{
    fprintf(token,"<DOUBLE, double>\n");
    fprintf(log_,"Line# %d: Token <DOUBLE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 334 "Lexical_Analyzer.l"
{
    fprintf(token,"<ELSE, else>\n");
    fprintf(log_,"Line# %d: Token <ELSE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 338 "Lexical_Analyzer.l"
{
    fprintf(token,"<FLOAT, float>\n");
    fprintf(log_,"Line# %d: Token <FLOAT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 342 "Lexical_Analyzer.l"
{
    fprintf(token,"<FOR, for>\n");
    fprintf(log_,"Line# %d: Token <FOR> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 346 "Lexical_Analyzer.l"
{
    fprintf(token,"<IF, if>\n");
    fprintf(log_,"Line# %d: Token <IF> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 350 "Lexical_Analyzer.l"
{
    fprintf(token,"<INT, int>\n");
    fprintf(log_,"Line# %d: Token <INT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 354 "Lexical_Analyzer.l"
{
    fprintf(token,"<RETURN, return>\n");
    fprintf(log_,"Line# %d: Token <RETURN> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 358 "Lexical_Analyzer.l"
{
    fprintf(token,"<SWITCH, switch>\n");
    fprintf(log_,"Line# %d: Token <SWITCH> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 362 "Lexical_Analyzer.l"
{
    fprintf(token,"<WHILE, while>\n");
    fprintf(log_,"Line# %d: Token <WHILE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 366 "Lexical_Analyzer.l"
{
    fprintf(token,"<VOID, void>\n");
    fprintf(log_,"Line# %d: Token <VOID> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 370 "Lexical_Analyzer.l"
{
    fprintf(token,"<ADDOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <ADDOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 374 "Lexical_Analyzer.l"
{
    fprintf(token,"<MULOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <MULOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 378 "Lexical_Analyzer.l"
{
    fprintf(token,"<RELOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <RELOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 382 "Lexical_Analyzer.l"
{
    fprintf(token,"<INCOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <INCOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 386 "Lexical_Analyzer.l"
{
    fprintf(token,"<LOGICOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <LOGICOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 390 "Lexical_Analyzer.l"
{
    fprintf(token,"<ASSIGNOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 394 "Lexical_Analyzer.l"
{
    fprintf(token,"<BITOP, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <BITOP> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 398 "Lexical_Analyzer.l"
{
    fprintf(token,"<NOT, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <NOT> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 402 "Lexical_Analyzer.l"
{
    fprintf(token,"<LPAREN, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 406 "Lexical_Analyzer.l"
{
    fprintf(token,"<RPAREN, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <RPAREN> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 410 "Lexical_Analyzer.l"
{
    fprintf(token,"<LCURL, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <LCURL> Lexeme %s found\n",line_count,yytext);
    Table.Enter_Scope();
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 415 "Lexical_Analyzer.l"
{
    fprintf(token,"<RCURL, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <RCURL> Lexeme %s found\n",line_count,yytext);
    Table.Exit_Scope();
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 420 "Lexical_Analyzer.l"
{
    fprintf(token,"<LSQUARE, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <LSQUARE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 424 "Lexical_Analyzer.l"
{
    fprintf(token,"<RSQUARE, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <RSQUARE> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 428 "Lexical_Analyzer.l"
{
    fprintf(token,"<COMMA, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <COMMA> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 432 "Lexical_Analyzer.l"
{
    fprintf(token,"<SEMICOLON, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <SEMICOLON> Lexeme %s found\n",line_count,yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 436 "Lexical_Analyzer.l"
{
                               
                                string formatted_s = StringFormatter(yytext);
                                fprintf(token, "<SINGLE LINE STRING, %s>\n", formatted_s.c_str());
                                fprintf(log_, "Line# %d: Token <SINGLE LINE STRING> Lexeme %s found\n", line_count, yytext);
                            }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 443 "Lexical_Analyzer.l"
{ 
                                string formatted_s = StringFormatter(yytext);
                                string temp_s=string(yytext);
                                fprintf(token, "<MULTI LINE STRING, %s>\n", formatted_s.c_str());
                                fprintf(log_, "Line# %d: Token <MULTI LINE STRING> Lexeme %s found\n", line_count, yytext);

                                for(int i = 0; i < temp_s.size(); ++i)
                                {
                                    if(temp_s[i] == '\n')
                                    {
                                        ++line_count;
                                    }
                                }
                            }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 458 "Lexical_Analyzer.l"
{
    fprintf(token,"<ID, %s>\n",yytext);
    fprintf(log_,"Line# %d: Token <ID> Lexeme %s found\n",line_count,yytext);
    if(Table.Insert(yytext,"ID",log_))
    {
        Table.printall(log_);
    }
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 466 "Lexical_Analyzer.l"
{
                            string temp_s = yytext;
                            if(temp_s.back() == '\n')
                            {
                                temp_s.pop_back();
                            }

                            if(temp_s.back() == '\r')
                            {
                                temp_s.pop_back();
                            }

                            fprintf(log_, "Line# %d: Token <SINGLE LINE COMMENT> Lexeme %s found\n", line_count, temp_s.c_str());

                            ++line_count;
                        }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 482 "Lexical_Analyzer.l"
{
                            string temp_com = yytext;
                            int additional_lines = 0;

                            if(temp_com.back() == '\n')
                            {
                                 temp_com.pop_back();
                                ++additional_lines;
                              
                            }

                            if(temp_com.back() == '\r')
                            {
                                temp_com.pop_back();
                            }

                            fprintf(log_, "Line# %d: Token <SINGLE LINE COMMENT> Lexeme %s found\n", line_count, temp_com.c_str());

                            line_count += additional_lines;

                            for(int i = 0; i < temp_com.size(); ++i)
                            {
                                if(temp_com[i] == '\n')
                                {
                                    ++line_count;
                                }
                            }
                        }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 511 "Lexical_Analyzer.l"
{
                            std::string temp_com = yytext;

                            fprintf(log_, "Line# %d: Token <MULTI LINE COMMENT> Lexeme %s found\n", line_count, temp_com.c_str());

                            for(int i = 0; i < comment.size(); ++i)
                            {
                                if(temp_com[i] == '\n')
                                {
                                    ++line_count;
                                }
                            }
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 526 "Lexical_Analyzer.l"
{
    error_count++;
    fprintf(log_,"Error at line# %d: TOO_MANY_DECIMAL_POINTS %s\n",line_count,yytext);

}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 531 "Lexical_Analyzer.l"
{
    error_count++;
    fprintf(log_,"Error at line# %d: ILLFORMED_NUMBER %s\n",line_count,yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 535 "Lexical_Analyzer.l"
{
     error_count++;
    fprintf(log_,"Error at line# %d: INVALID_ID_SUFFIX_NUM_PREFIX %s\n",line_count,yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 539 "Lexical_Analyzer.l"
{
     error_count++;
    fprintf(log_,"Error at line# %d: EMPTY_CONST_CHAR %s\n",line_count,yytext);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 543 "Lexical_Analyzer.l"
{
     error_count++;
    fprintf(log_,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n",line_count,yytext);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 547 "Lexical_Analyzer.l"
{
     error_count++;
    fprintf(log_,"Error at line# %d: MULTICHAR_CONSTANT_CHAR %s\n",line_count,yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 551 "Lexical_Analyzer.l"
{
     error_count++;
    fprintf(log_,"Error at line# %d: UNRECOGNISED CHAR %s\n",line_count,yytext);
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 555 "Lexical_Analyzer.l"
{
                        string temp_s = yytext;

                        for(int i = 0; i < temp_s.size(); ++i)
                        {
                            if(temp_s[i] == '\n')
                            {
                                ++line_count;
                            }
                        }

                        fprintf(log_, "Error at line# %d: UNFINISHED_STRING %s\n", line_count, yytext);

                        ++error_count;
                    }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 571 "Lexical_Analyzer.l"
{
                            string temp_s= yytext;

                            for(int i = 0; i < temp_s.size(); ++i)
                            {
                                if(temp_s[i] == '\n')
                                {
                                    ++line_count;
                                }
                            }

                            fprintf(log_, "Error at line# %d: UNFINISHED_COMMENT %s\n", line_count, yytext);

                            ++error_count;
                        } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 586 "Lexical_Analyzer.l"
ECHO;
	YY_BREAK
#line 1670 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment_state):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 225 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 225 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 224);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 586 "Lexical_Analyzer.l"

int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	
	yyin= fin;
	yylex();
    Table.printall(log_);
	fprintf(log_,"\nTotal Lines : %d\nTotal Errors : %d\n",line_count,error_count);
	fclose(yyin);
	fclose(token);
	fclose(log_);
	return 0;
}
